### ISSUE TITLE
Remove dependency on com.vasileff.ceylon.xmath

### ISSUE THREAD

**Issue by renatoathaydes** [jvasileff/ceylon-random#1]
Hi!

I like your random library and want to contribute some code to it...

But before I get to that, I hope you don't mind if I give some suggestions. For example, I think it's not a good idea to mix this library with your xmath library. The Random library has the potential to become the de-facto random library in Ceylon, but if you start demanding people who only need a silly random generator to get a few things a little less deterministic to download more than one library (and this case it would be a `shared import`) this may make it more troublesome than it should be.

My suggestion would be to create some random generators in the `xmath` library itself, or even make it fully modular and have a `xmath.random` module with random functions that work with `xmath` and integrates with `random`.

**Comment by jvasileff** [comment]
Thanks Renato!

I don't have a problem with non-`shared` dependencies in general as long as they're on Herd, but I do agree with you here.

It's currently required on `next` since I thought about using `Long` to make the JVM and JS implementations of `LCGRandom` identical. But instead, just using different parameters and accepting a shorter cycle length on JS is probably the better approach.

**Comment by jvasileff** [comment]
Fixed!
